#!/usr/bin/env bash
# Install the `manfred` command: a launcher that boots the backend + terminal UI.
# Installs a small shim into ~/.local/bin that runs this clone's venv.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$REPO/src"
BIN="${MANFRED_BIN_DIR:-$HOME/.local/bin}"

echo "Syncing dependencies…"
( cd "$SRC" && uv sync )

mkdir -p "$BIN"
SHIM="$BIN/manfred"
cat > "$SHIM" <<EOF
#!/usr/bin/env bash
# Generated by manfred_backend/install.sh — runs the launcher from this clone.
cd "$SRC" || exit 1
exec "$SRC/.venv/bin/python" -m app.cli.launcher "\$@"
EOF
chmod +x "$SHIM"

echo "Installed: $SHIM"
case ":$PATH:" in
  *":$BIN:"*) echo "Run: manfred" ;;
  *) echo "warning: $BIN is not on your PATH. Add it, e.g.:"
     echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc" ;;
esac
