"""empty message

Revision ID: d2b70d60cda9
Revises: 7c1b4f4d7c2a
Create Date: 2026-04-08 08:03:02.155518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b70d60cda9'
down_revision: Union[str, Sequence[str], None] = '7c1b4f4d7c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('source_call_id', sa.String(length=64), nullable=True))
    op.add_column(
        'agents',
        sa.Column('waiting_for', sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'waiting_for')
    op.drop_column('agents', 'source_call_id')
    # ### end Alembic commands ###
