"""Shared alarm hotword taxonomy for sensor operator_notes classification."""

from __future__ import annotations

ALARM_HOTWORDS: list[str] = [
    "troubleshooting",
    "doubtful",
    "should be investigated",
    "investigation is completed",
    "under investigation",
    "suspicious",
    "quality audit",
    "unreliable",
    "urgent verification",
    "unusual",
    "escalated",
    "maintenance follow-up",
    "root-cause analysis",
    "flagged it",
    "quality control",
    "probable fault",
    "potential fault",
    "diagnostic task",
    "engineering analysis",
    "degradation",
    "signs of malfunction",
    "signs of an issue",
    "instability",
    "unstable",
    "irregularity",
    "inconsistency",
    "inconsistent",
    "compromised",
    "anomaly check",
    "visible anomaly",
    "behavior is concerning",
    "raises serious doubts",
    "not trustworthy",
    "not comfortable",
    "did not look right",
    "does not match healthy",
    "does not look healthy",
    "not the pattern i expected",
    "outside expected behavior",
    "conflicts with our baseline",
    "safety-minded review",
    "consistency is clearly broken",
    "cannot be treated as normal",
    "requires attention",
    "questionable behavior",
    "replacement assessment",
    "revalidation",
    "on-site inspection",
    "technicians to inspect",
    "unexpected pattern",
    "confidence in this report is low",
    "changed in a risky way",
    "stream contains signs",
    "operating picture is not trustworthy",
    "pattern indicates probable",
]
